### ISSUE TITLE
Пропали изображения постеров и др.

### ISSUE THREAD

**Issue by rub1kv** [Sheinices/Prisma_ATVGTV#1]
Здравствуйте!

Пропали постеры и все другие изображения в приложении. Буду благодарен исправлению.

**Comment by Sheinices** [comment]
Здравствуйте! Я заметил, сегодня исправлю

**Comment by Sheinices** [comment]
Исправил

**Comment by sbdevapp** [comment]
Спасибо, картинки появились, а сегодня - снова та же проблема...

**Comment by Sheinices** [comment]
Здравствуйте! Кэш почистил, попробуйте

**Comment by sbdevapp** [comment]
На пару часов проблема ушла и вновь исчезли все изображения из приложения... Обновление до версии 0.3.5 не помогло...

**Comment by Sheinices** [comment]
Сегодня разобрался с проблемой. Если в приложении не появились картинки, рекомендую почистить кэш в настройках
