### ISSUE TITLE
Не выходит из приложения по кнопке back

### ISSUE THREAD

**Issue by F7799** [Sheinices/Prisma_ATVGTV#2]

**Comment by Sheinices** [comment]
Здравствуйте! Смотря какое устройство у вас.

**Comment by Sheinices** [comment]
Если у вас не оригинальный пульт от устройства может не работать выход. Пульт с мышью аналогично не будет работать кнопкой назад.
Единственный способ это долгое удержания кнопки назад или домик.

**Comment by F7799** [comment]
Спасибо,но хотелось бы fix it

**Comment by Sheinices** [comment]
Постараюсь реализовать

**Comment by bronenos** [comment]
Присоединяюсь к просьбе

Использую на SberBox, но управляю родным пультом от SamsungTV через HDMI-CEC

Через пульт от SberBox длительный Back работает, а SamsungTV вероятно не прокидывает длительное Back в SberBox

В связи с чем было бы здорово заиметь кнопку выхода в интерфейсе или реакцию на Back из корневого состояния UI, а то очень уж тяжко

Благодарю за внимание

**Comment by Sheinices** [comment]
Как будет время попробую что-нибудь придумать

**Comment by Sheinices** [comment]
Реализовал выход из приложения. Иконка для быстрого выхода радом с поиском. Для работы обновите приложение.

**Comment by F7799** [comment]
Отлично работает! Замечательно.
