### ISSUE TITLE
Завис сайт. Не идёт загрузка.

### ISSUE THREAD

**Issue by F7799** [Sheinices/Prisma_ATVGTV#4]

**Comment by Sheinices** [comment]
Работа идет

**Comment by F7799** [comment]
Ок. Все работает.

**Comment by Spam-box-ua** [comment]
Пропала Rezka как источник.
Извини не шарю как с тобой связаться чтобы спросить об этом. Поэтому написал тут. Новый тикет не стал создавать. Приходи на 4pda, обратная связь будет лучше.

**Comment by Sheinices** [comment]
Здравствуйте! Резка все. Блокируют всех, пока отключено.

**Comment by Sheinices** [comment]
Пока времени нет что-то придумать с ней.

**Comment by Spam-box-ua** [comment]
Есть неофициальное приложение Hdrezka,  в телеге есть группа "Hdrezka неофициальное приложение" там разработчик 4nk1r. Он знает как с этим бороться. 
Я написал ему про твой проект, может поможет, а может нет.

**Comment by Sheinices** [comment]
Спасибо. Я понимаю как можно обойти. На все время нужно найти )

**Comment by Sheinices** [comment]
Резку вроде сделал. Посмотрим как будет работать

**Comment by F7799** [comment]
Ок. Резка идёт в 4к.

**Comment by Spam-box-ua** [comment]
За Rezka спасибо. Ещё было бы неплохо если бы открыл комментарии к постам в телеграмме, гитхаб вроде не чат. Тупо как-то писать подобные текущему посты. Или не тупо? И что на счёт 4pda надумал?

**Comment by Sheinices** [comment]
Посмотрю. Чат сделаю или комментарии включу
