### ISSUE TITLE
фильтр не выдает результат 

### ISSUE THREAD

**Issue by yuipp** [Sheinices/Prisma_ATVGTV#5]
Запускаю приложение, нажимаю фильтр - выбираю любой параметр, например фильмы, год 1992, нажимаю начать поиск и выдает "этот список пуст", что может быть?

LOS 20 А13 планшет Samsung

**Comment by yuipp** [comment]
удалил полностью и поставил заново - стало меньше опций фильтров но теперь ок! 🍻

**Comment by Sheinices** [comment]
Я рад что разобрались) 
Возможно глюк был
