### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Benefic** [Sheinices/Prisma_ATVGTV#6]
Как на счёт контрибуции? У меня Xiaomi TV, есть некоторые проблемы. Я бы мог их отловить и сделать PR с исправлениями.
В частности 
- при запуске воспроизведения первого эпизода сериала включается оригинальная аудио дорожка. Перевыбор русской без переключения исправляет ситуацию.
- при перемотке до конца эпизода не происходит переключение на следующий (переключается, но не начинается воспроизведение, висит в анимации загрузки 
- в меню фильтр при выборе сериалов за диапазон лет, вылетает (иногда с перезагрузкой всего ТВ)
- при выборе источника 1080 (collapse) видео запускается в 720, надо переключать

**Comment by Sheinices** [comment]
Здравствуйте. С аудио и качеством у collaps это происходит?
По поводу фильтра знаю ситуацию, буду исправлять

**Comment by Sheinices** [comment]
Переключение на следующую серию на xiaomi давно исправил. Попробуйте кэш очистить. Сейчас ещё на 3 устройства проверил все работает отлично.

**Comment by Benefic** [comment]
> Здравствуйте. С аудио и качеством у collaps это происходит? По поводу фильтра знаю ситуацию, буду исправлять

Да, collaps

**Comment by Benefic** [comment]
> Переключение на следующую серию на xiaomi давно исправил. Попробуйте кэш очистить. Сейчас ещё на 3 устройства проверил все работает отлично.

Я попробую, но приложение в принципе впервые с нуля вчера поставил. Тут что-то другое

**Comment by Sheinices** [comment]
У collaps включен dash 1080p. Есть такой прикол с озвучкой и что качество авто не работает. Могу вернуть в 720p чтобы корректно работало.

**Comment by Sheinices** [comment]
Ошибку в фильтре пофиксил
