### ISSUE TITLE
Нет подключения к TorrServer

### ISSUE THREAD

**Issue by upais** [Sheinices/Prisma_ATVGTV#7]
Добрый день.

При попытке открыть воспроизведение через торрент возникает сообщение, что нечем его открыть. Естественно, TorrServer установлен и точно работает так как Lampa с ним успешно взаимодействует. А вот в Prisma настроек указания TorrServ не вижу, вероятно, оно само находит его и подключается, но не в моем случае, хотя висит он на стандартном 8090, в той же сети, авторизации нет.

**Comment by Sheinices** [comment]
Здравствуйте. Только что проверил на разных тв и мобильных. Все работает
Кэш очистить или переустановить приложение

**Comment by Sheinices** [comment]
Да действительно где-то не работает. Сегодня посмотрю

**Comment by upais** [comment]
Я еще на 4pda встречал, что у кого-то работает у кого-то нет.
Еще мысль пришла, что может там речь не про TorrServer, а про проигрыватель? Я пробовал только встроенный, а через Vimu не догадался.

Приложение только установил и сразу эта ситуация.

**Comment by Sheinices** [comment]
Вроде исправил. Вчера данные переносил на другой сервер, возможно где-то обкосячился.)

**Comment by Sheinices** [comment]
Да это косяк был через встроенный плеер, сейчас поправил. А вообще для торрентов лучше "Виму" использовать

**Comment by upais** [comment]
Бывает :)
Вечером проверю, отпишусь. Спасибо!

Встроенный по интерфейсу проще для домашних пользователей, по этому пробую через него. А я ведь правильно додумал, он пытается найти TorrServer в локальной сети или там забит адрес какого-то внешнего?

**Comment by Sheinices** [comment]
Адрес сервера прописан, а если нет доступа пробует подключиться на стороне клиента

**Comment by upais** [comment]
Так и не заработало. Обновился на 0.4.4, выбрал внешний плеер, разные раздачи - ничего не меняется.
![IMG_0240 JPG_compressed](https://github.com/Sheinices/Prisma_TV/assets/86227709/f3003fa6-70df-4c0f-a419-98e30225afc7)
