### ISSUE TITLE
Закрывается клавиатура в поиске

### ISSUE THREAD

**Issue by rub1kv** [Sheinices/Prisma_ATVGTV#8]
Здравствуйте!

При попытке ввода названия фильма в поиске клавиатура каждый раз закрывается, поэтому фильм ввести не удается. Видео с проблемой - https://dropmefiles.com/GsNcf (файл не загрузился на гит, т.к. больше 10 Мб). Версия приложения последняя. До этого стояла версия 0.3.6, там такой проблемы вроде не было. Буду рад фиксу, заранее огромное спасибо.

**Comment by Sheinices** [comment]
Если новую версию переустановили. Попробуйте кэш почистить. Как вариант клавиатуру другую поставить LeanKey Keyboard если android tv

**Comment by Sheinices** [comment]
Думаю единичный случай у вас

**Comment by rub1kv** [comment]
Проверил, проблема была и на версии 0.3.6, просто там я нажимал на микрофон в поиске, а потом вводил текст во всплывающем окошке. В этом случае клавиатура не закрывается и в последней версии. 

А вот если вводить текст в поисковой строке без нажатия микрофона - то после нажатия стрелки на пульте - клавиатура закрывается, будто бы уходит фокус с текстового поля. При этом если набирать текст аэромышкой, а не кнопками на пульте, то все работает. То есть проблема с закрытием клавиатуры вызывается именно нажатием стрелок на пульте.

На всякий случай полностью удалил приложение, установил ещё раз. Проблема осталась, то есть дело не в кэше.

Буду очень рад если удастся понять в чем причина и пофиксить. Могу быть оперативным бета-тестером (могу держать связь в Tg или где удобно). С радостью задоначу за решение проблемы. Очень важно её решить. Заранее спасибо!

**Comment by rub1kv** [comment]
![2024-05-14 10 04 22](https://github.com/Sheinices/Prisma_TV/assets/35856066/e6018e9b-405b-4065-9544-3b54ede16f33)
В теме приложения на 4PDA нашел сообщение об аналогичной проблеме, правда на другой модели приставки. Очень хочется фикса. Заранее спасибо :)

**Comment by Sheinices** [comment]
Под определенный вид приставок я к сожалению не сделаю. Позже добавляю встроенную клавиатуру

**Comment by rub1kv** [comment]
Спасибо за решение со встроенной клавиатурой. Пока неизвестно когда примерно она появится?

Странно, что проблема именно в Prisma, в других приложениях (в т.ч. для просмотра фильмов) - клавиатура работает корректно. Да и даже в Prisma она раблотает корректно, если открыть окно для голосового ввода.

**Comment by Sheinices** [comment]
Сегодня реализую

**Comment by Sheinices** [comment]
> Спасибо за решение со встроенной клавиатурой. Пока неизвестно когда примерно она появится?
> 
> Странно, что проблема именно в Prisma, в других приложениях (в т.ч. для просмотра фильмов) - клавиатура работает корректно. Да и даже в Prisma она раблотает корректно, если открыть окно для голосового ввода.

Добавил клавиатуру. В настройках можете выбрать (Настройки -> Остальные)
